version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-animated-portfolio
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
